export type ScenarioLevel = 'beginner' | 'intermediate' | 'advanced';

export interface Scenario {
  id: string;
  titleEn: string;
  titleKo: string;
  descriptionEn: string;
  emoji: string;
  level: ScenarioLevel;
  estimatedMinutes: number;
  isPremium: boolean;
}

export const SCENARIOS: Scenario[] = [
  // Beginner (초급)
  {
    id: 'cafe_order',
    titleEn: 'Ordering at a Café',
    titleKo: '카페에서 주문하기',
    descriptionEn: 'Practice ordering coffee and snacks in Korean',
    emoji: '☕',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'self_intro',
    titleEn: 'Self Introduction',
    titleKo: '자기소개',
    descriptionEn: 'Introduce yourself in Korean',
    emoji: '👋',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'ask_directions',
    titleEn: 'Asking for Directions',
    titleKo: '길 묻기',
    descriptionEn: 'Find your way around Korean streets',
    emoji: '🗺️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'ask_price',
    titleEn: 'Shopping & Prices',
    titleKo: '물건 사기 & 가격 묻기',
    descriptionEn: 'Shop and negotiate prices',
    emoji: '🛍️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'make_appointment',
    titleEn: 'Making an Appointment',
    titleKo: '약속 잡기',
    descriptionEn: 'Schedule a time to meet a friend',
    emoji: '📅',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'restaurant_order',
    titleEn: 'At a Restaurant',
    titleKo: '식당에서 주문',
    descriptionEn: 'Order food and ask about the menu',
    emoji: '🍜',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'taxi_ride',
    titleEn: 'Taking a Taxi',
    titleKo: '택시 타기',
    descriptionEn: 'Direct a taxi driver to your destination',
    emoji: '🚕',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'convenience_store',
    titleEn: 'Convenience Store',
    titleKo: '편의점에서',
    descriptionEn: 'Buy items at a Korean convenience store',
    emoji: '🏪',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'phone_call',
    titleEn: 'Making a Phone Call',
    titleKo: '전화 통화',
    descriptionEn: 'Make a simple phone call in Korean',
    emoji: '📱',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'weather_chat',
    titleEn: 'Talking About Weather',
    titleKo: '날씨 이야기',
    descriptionEn: 'Chat about the weather',
    emoji: '☀️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  // Intermediate (중급)
  {
    id: 'friend_meetup',
    titleEn: 'Meeting a Friend',
    titleKo: '친구와 약속',
    descriptionEn: 'Plan and discuss activities with a friend',
    emoji: '👫',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'restaurant_recommend',
    titleEn: 'Getting a Restaurant Recommendation',
    titleKo: '맛집 추천 받기',
    descriptionEn: 'Ask for and discuss restaurant recommendations',
    emoji: '🍽️',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'korean_culture',
    titleEn: 'Discussing Korean Culture',
    titleKo: '한국 문화 이야기',
    descriptionEn: 'Talk about K-pop, K-dramas, and Korean traditions',
    emoji: '🎭',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'health_doctor',
    titleEn: 'At the Doctor',
    titleKo: '병원에서',
    descriptionEn: 'Describe symptoms and get medical advice',
    emoji: '🏥',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'bank_visit',
    titleEn: 'Visiting a Bank',
    titleKo: '은행 방문',
    descriptionEn: 'Handle basic banking transactions',
    emoji: '🏦',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  // Advanced (고급)
  {
    id: 'job_interview',
    titleEn: 'Job Interview',
    titleKo: '취업 면접',
    descriptionEn: 'Practice for a Korean company job interview',
    emoji: '💼',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'news_debate',
    titleEn: 'Discussing Korean News',
    titleKo: '한국 뉴스 토론',
    descriptionEn: 'Debate current events and social issues',
    emoji: '📰',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'kdrama_reenact',
    titleEn: 'K-Drama Scene Reenactment',
    titleKo: 'K-드라마 장면 재연',
    descriptionEn: 'Reenact scenes from popular K-dramas',
    emoji: '🎬',
    level: 'advanced',
    estimatedMinutes: 10,
    isPremium: true,
  },
  {
    id: 'business_meeting',
    titleEn: 'Business Meeting',
    titleKo: '비즈니스 미팅',
    descriptionEn: 'Conduct a professional business discussion',
    emoji: '🤝',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'university_lecture',
    titleEn: 'University Discussion',
    titleKo: '대학 토론',
    descriptionEn: 'Participate in an academic discussion',
    emoji: '🎓',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
] as const;

export const LEVEL_LABELS: Record<ScenarioLevel, string> = {
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
};

export const LEVEL_COLORS: Record<ScenarioLevel, string> = {
  beginner: '#10B981',
  intermediate: '#3B82F6',
  advanced: '#8B5CF6',
};
