export type ScenarioLevel = 'beginner' | 'intermediate' | 'advanced';

export interface Scenario {
  id: string;
  titleEn: string;
  titleKo: string;
  descriptionEn: string;
  emoji: string;
  level: ScenarioLevel;
  estimatedMinutes: number;
  isPremium: boolean;
}

export const SCENARIOS: Scenario[] = [
  // ── Beginner (초급) ─────────────────────────────────────────
  {
    id: 'cafe_order',
    titleEn: 'Ordering at a Café',
    titleKo: '카페에서 주문하기',
    descriptionEn: 'Practice ordering coffee and snacks in Korean',
    emoji: '☕',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'self_intro',
    titleEn: 'Self Introduction',
    titleKo: '자기소개',
    descriptionEn: 'Introduce yourself in Korean',
    emoji: '👋',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'ask_directions',
    titleEn: 'Asking for Directions',
    titleKo: '길 묻기',
    descriptionEn: 'Find your way around Korean streets',
    emoji: '🗺️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'ask_price',
    titleEn: 'Shopping & Prices',
    titleKo: '물건 사기 & 가격 묻기',
    descriptionEn: 'Shop and negotiate prices',
    emoji: '🛍️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'make_appointment',
    titleEn: 'Making an Appointment',
    titleKo: '약속 잡기',
    descriptionEn: 'Schedule a time to meet a friend',
    emoji: '📅',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'restaurant_order',
    titleEn: 'At a Restaurant',
    titleKo: '식당에서 주문',
    descriptionEn: 'Order food and ask about the menu',
    emoji: '🍜',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'taxi_ride',
    titleEn: 'Taking a Taxi',
    titleKo: '택시 타기',
    descriptionEn: 'Direct a taxi driver to your destination',
    emoji: '🚕',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'convenience_store',
    titleEn: 'Convenience Store',
    titleKo: '편의점에서',
    descriptionEn: 'Buy items at a Korean convenience store',
    emoji: '🏪',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'phone_call',
    titleEn: 'Making a Phone Call',
    titleKo: '전화 통화',
    descriptionEn: 'Make a simple phone call in Korean',
    emoji: '📱',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'weather_chat',
    titleEn: 'Talking About Weather',
    titleKo: '날씨 이야기',
    descriptionEn: 'Chat about the weather',
    emoji: '☀️',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'subway_bus',
    titleEn: 'Subway & Bus',
    titleKo: '지하철·버스 타기',
    descriptionEn: 'Navigate Korean public transport',
    emoji: '🚇',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'pharmacy',
    titleEn: 'At the Pharmacy',
    titleKo: '약국 방문',
    descriptionEn: 'Describe symptoms and buy medicine',
    emoji: '💊',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'hotel_checkin',
    titleEn: 'Hotel Check-in',
    titleKo: '호텔 체크인',
    descriptionEn: 'Check into a Korean hotel smoothly',
    emoji: '🏨',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'lost_item',
    titleEn: 'Lost & Found',
    titleKo: '분실물 찾기',
    descriptionEn: 'Report a lost item and ask for help',
    emoji: '😰',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'grocery_store',
    titleEn: 'Grocery Shopping',
    titleKo: '마트 장보기',
    descriptionEn: 'Buy groceries and ask where things are',
    emoji: '🛒',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'haircut',
    titleEn: 'At the Hair Salon',
    titleKo: '미용실 방문',
    descriptionEn: 'Describe the hairstyle you want',
    emoji: '💇',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'post_office',
    titleEn: 'Post Office',
    titleKo: '우체국 이용',
    descriptionEn: 'Send a package or buy stamps',
    emoji: '📮',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'movie_ticket',
    titleEn: 'Buying Movie Tickets',
    titleKo: '영화 예매',
    descriptionEn: 'Book cinema tickets and find your seat',
    emoji: '🎥',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'gym_registration',
    titleEn: 'Joining a Gym',
    titleKo: '헬스장 등록',
    descriptionEn: 'Sign up for a gym membership',
    emoji: '💪',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },
  {
    id: 'korean_food',
    titleEn: 'Talking About Korean Food',
    titleKo: '한국 음식 이야기',
    descriptionEn: 'Discuss your favourite Korean dishes',
    emoji: '🥘',
    level: 'beginner',
    estimatedMinutes: 5,
    isPremium: false,
  },

  // ── Intermediate (중급) ────────────────────────────────────────
  {
    id: 'friend_meetup',
    titleEn: 'Meeting a Friend',
    titleKo: '친구와 약속',
    descriptionEn: 'Plan and discuss activities with a friend',
    emoji: '👫',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'restaurant_recommend',
    titleEn: 'Getting a Restaurant Recommendation',
    titleKo: '맛집 추천 받기',
    descriptionEn: 'Ask for and discuss restaurant recommendations',
    emoji: '🍽️',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'korean_culture',
    titleEn: 'Discussing Korean Culture',
    titleKo: '한국 문화 이야기',
    descriptionEn: 'Talk about K-pop, K-dramas, and Korean traditions',
    emoji: '🎭',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'health_doctor',
    titleEn: 'At the Doctor',
    titleKo: '병원에서',
    descriptionEn: 'Describe symptoms and get medical advice',
    emoji: '🏥',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'bank_visit',
    titleEn: 'Visiting a Bank',
    titleKo: '은행 방문',
    descriptionEn: 'Handle basic banking transactions',
    emoji: '🏦',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'travel_planning',
    titleEn: 'Planning a Trip',
    titleKo: '여행 계획 짜기',
    descriptionEn: 'Discuss a trip itinerary inside Korea',
    emoji: '✈️',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'cooking_class',
    titleEn: 'Learning to Cook Korean Food',
    titleKo: '한국 요리 배우기',
    descriptionEn: 'Follow a recipe and ask cooking questions',
    emoji: '👩‍🍳',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'customer_complaint',
    titleEn: 'Customer Complaint',
    titleKo: '불만 접수하기',
    descriptionEn: 'Handle a complaint about a product or service',
    emoji: '😤',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'house_hunting',
    titleEn: 'House Hunting',
    titleKo: '집 구하기',
    descriptionEn: 'Ask about an apartment and negotiate terms',
    emoji: '🏠',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'language_partner',
    titleEn: 'Language Exchange',
    titleKo: '언어 교환 파트너',
    descriptionEn: 'Chat with a Korean language exchange partner',
    emoji: '🌍',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'workplace_chat',
    titleEn: 'Workplace Conversation',
    titleKo: '직장 동료와 대화',
    descriptionEn: 'Small talk and discussions in a Korean office',
    emoji: '💬',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'emergency_help',
    titleEn: 'Emergency Situation',
    titleKo: '긴급 상황 대처',
    descriptionEn: 'Ask for urgent help in Korean',
    emoji: '🆘',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'study_abroad',
    titleEn: 'Studying in Korea',
    titleKo: '한국 유학 정보',
    descriptionEn: 'Ask about university admission and campus life',
    emoji: '📚',
    level: 'intermediate',
    estimatedMinutes: 10,
    isPremium: false,
  },
  {
    id: 'hobby_share',
    titleEn: 'Sharing a Hobby',
    titleKo: '취미 이야기',
    descriptionEn: 'Talk about your hobbies and ask about theirs',
    emoji: '🎨',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },
  {
    id: 'online_shopping',
    titleEn: 'Online Shopping Issue',
    titleKo: '온라인 쇼핑 문제',
    descriptionEn: 'Resolve a delivery or return problem',
    emoji: '📦',
    level: 'intermediate',
    estimatedMinutes: 8,
    isPremium: false,
  },

  // ── Advanced (고급, Pro) ─────────────────────────────────────
  {
    id: 'job_interview',
    titleEn: 'Job Interview',
    titleKo: '취업 면접',
    descriptionEn: 'Practice for a Korean company job interview',
    emoji: '💼',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'news_debate',
    titleEn: 'Discussing Korean News',
    titleKo: '한국 뉴스 토론',
    descriptionEn: 'Debate current events and social issues',
    emoji: '📰',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'kdrama_reenact',
    titleEn: 'K-Drama Scene Practice',
    titleKo: 'K-드라마 장면 연습',
    descriptionEn: 'Practise dramatic and emotional Korean expressions',
    emoji: '🎬',
    level: 'advanced',
    estimatedMinutes: 10,
    isPremium: true,
  },
  {
    id: 'business_meeting',
    titleEn: 'Business Meeting',
    titleKo: '비즈니스 미팅',
    descriptionEn: 'Conduct a professional business discussion',
    emoji: '🤝',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'university_lecture',
    titleEn: 'University Discussion',
    titleKo: '대학 토론',
    descriptionEn: 'Participate in an academic discussion',
    emoji: '🎓',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'legal_consultation',
    titleEn: 'Legal Consultation',
    titleKo: '법률 상담',
    descriptionEn: 'Discuss a legal matter with a Korean advisor',
    emoji: '⚖️',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'investment_advice',
    titleEn: 'Investment Talk',
    titleKo: '투자 상담',
    descriptionEn: 'Discuss Korean stocks, real estate, or funds',
    emoji: '📈',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'medical_consultation',
    titleEn: 'Medical Consultation',
    titleKo: '의료 상담',
    descriptionEn: 'Get a detailed medical second opinion',
    emoji: '🩺',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'social_issue_debate',
    titleEn: 'Social Issues Debate',
    titleKo: '사회 이슈 토론',
    descriptionEn: 'Argue opinions on contemporary Korean society',
    emoji: '💭',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
  {
    id: 'startup_pitch',
    titleEn: 'Startup Pitch',
    titleKo: '스타트업 피치',
    descriptionEn: 'Pitch your business idea to a Korean investor',
    emoji: '🚀',
    level: 'advanced',
    estimatedMinutes: 15,
    isPremium: true,
  },
] as const;

export const LEVEL_LABELS: Record<ScenarioLevel, string> = {
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  advanced: 'Advanced',
};

export const LEVEL_COLORS: Record<ScenarioLevel, string> = {
  beginner: '#10B981',
  intermediate: '#3B82F6',
  advanced: '#8B5CF6',
};
